version: '3.1'

services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: mvg
      POSTGRES_PASSWORD: 3krRMhNa
      POSTGRES_DB: mvg
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: