apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: mvg-pgadmin-ingress
  namespace: mvg
spec:
  entryPoints:
    - websecure
  routes:
  - match: Host(`pgadmin.mvg.life`)
    kind: Rule
    services:
    - name: pgadmin
      port: 80
  tls:
    certResolver: letsencrypt