apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: mvg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4:latest
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          value: "linus@r13.de"
        - name: PGADMIN_DEFAULT_PASSWORD
          value: "g45z55VPAAEL"
        ports:
        - containerPort: 80
